### ISSUE TITLE
It'is not working on background app

### ISSUE THREAD

**Issue by adsizmusa** [4Q-s-r-o/call_log#15] opened 2021-01-31 13:24 UTC
I use the plugin in my flutter project

It is very good working on runtime 

but I want to run this plugin  on background service

İt give this error

` Attempt to invoke virtual method 'int android.app.Activity.checkSelfPermission(java.lang.String)' on a null object reference`

**Comment by adsizmusa** [comment] 2021-02-02 13:14
I have the same problem

![image](https://user-images.githubusercontent.com/56891037/106605160-a4787680-6571-11eb-852e-5c7c54a07b57.png)

**Comment by MartinHlavna** [comment] 2021-02-04 08:31
Closing as duplicate of #11. Feel free to track progress there.

**Closed by MartinHlavna** 2021-02-04 08:31 UTC
